const c=document.getElementById('game'),x=c.getContext('2d');
const ui={wave:document.getElementById('wave'),score:document.getElementById('score'),hp:document.getElementById('hp'),armor:document.getElementById('armor'),ammo:document.getElementById('ammo'),reloadText:document.getElementById('reloadText'),start:document.getElementById('startScreen'),dead:document.getElementById('deadScreen'),up:document.getElementById('upgradeScreen'),upgrades:document.getElementById('upgrades'),finalScore:document.getElementById('finalScore'),finalWave:document.getElementById('finalWave'),killfeed:document.getElementById('killfeed'),flash:document.getElementById('flash'),play:document.getElementById('play'),again:document.getElementById('again')};
let W=0,H=0,D=1,last=0,running=false,paused=true,reloading=false,reloadT=0,muzzle=0,damageFlash=0;
const keys={};let touch={mx:0,my:0,lookId:null,lastX:0,fire:false};
const MW=19,MH=19;
const map=[
'###################','#####........#####','#####.#######.#####','###...#.....#...###','###.#.#.###.#.#.###','...#.#.#...#.#.#...','##.#.#.#####.#.#.##','##...#...#...#...##','####.###.#.###.####','....#....P....#....','####.###.#.###.####','##...#...#...#...##','##.#.#.#####.#.#.##','...#.#.#...#.#.#...','###.#.#.###.#.#.###','###...#.....#...###','#####.#######.#####','#####.........#####','###################'];
const world={cell:64};
const state={wave:1,score:0,kills:0,spawn:0,spawnTimer:0,enemies:[],bullets:[],enemyBullets:[],parts:[],player:null,weapon:{mag:12,reserve:84,fireCd:0,damage:28,fireRate:7.3,crit:.08},upg:{dmg:1,rate:1,armor:1,move:1,dash:1,crit:0},arenaAngle:0};
const enemyTypes={grunt:{hp:55,speed:1.25,range:7,dmg:8,color:'#d6e0e8',size:.38,score:100},runner:{hp:34,speed:2.15,range:7,dmg:11,color:'#ff586f',size:.31,score:140},heavy:{hp:135,speed:.72,range:6,dmg:14,color:'#70a7c3',size:.5,score:240}};
const upgrades=[
['WEAPON','APEX ROUNDS','Mermi hasarı +35%.',()=>state.weapon.damage*=1.35],['WEAPON','RAPID CYCLER','Ateş hızı +18%.',()=>state.weapon.fireRate*=1.18],['DEFENSE','HARDPLATE','Maksimum armor +30 ve anında yenile.',()=>{state.player.maxArmor+=30;state.player.armor=state.player.maxArmor}],['MOBILITY','VECTOR','Hareket hızı +18%.',()=>state.upg.move*=1.18],['TACTIC','CRITICAL PATH','Kritik şansı +10%.',()=>state.weapon.crit+=.1],['TACTIC','PHASE DASH','Dash cooldown daha kısa.',()=>state.upg.dash*=1.3]
];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)), dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y), norm=a=>{const l=Math.hypot(a.x,a.y)||1;return{x:a.x/l,y:a.y/l}};
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;c.style.width=W+'px';c.style.height=H+'px';x.setTransform(D,0,0,D,0,0);world.cell=Math.min(72,Math.max(58,W/12));}
addEventListener('resize',resize);addEventListener('orientationchange',()=>setTimeout(resize,100));resize();
function tileAt(tx,ty){if(tx<0||ty<0||tx>=MW||ty>=MH)return '#';return map[ty][tx]||'#'}
function solid(px,py){return tileAt(Math.floor(px/world.cell),Math.floor(py/world.cell))==='#'}
function canMove(px,py,r=.16){return !solid(px-r*world.cell,py-r*world.cell)&&!solid(px+r*world.cell,py-r*world.cell)&&!solid(px-r*world.cell,py+r*world.cell)&&!solid(px+r*world.cell,py+r*world.cell)}
function worldToPx(tx,ty){return{x:(tx+.5)*world.cell,y:(ty+.5)*world.cell}}
function reset(){state.wave=1;state.score=0;state.kills=0;state.spawn=0;state.spawnTimer=.5;state.enemies=[];state.bullets=[];state.enemyBullets=[];state.parts=[];state.weapon={mag:12,reserve:84,fireCd:0,damage:28,fireRate:7.3,crit:.08};state.upg={dmg:1,rate:1,armor:1,move:1,dash:1,crit:0};state.player={x:worldToPx(9,9).x,y:worldToPx(9,9).y,a:0,hp:100,maxHp:100,armor:75,maxArmor:75,move:2.8,dashCd:0,inv:0};reloading=false;paused=false;ui.start.classList.remove('show');ui.dead.classList.remove('show');ui.up.classList.remove('show');startWave();updateUI()}
function startWave(){state.spawn=8+state.wave*3;state.spawnTimer=.3;toast('WAVE '+String(state.wave).padStart(2,'0'))}
function toast(t){const d=document.createElement('div');d.className='feedItem';d.textContent=t;ui.killfeed.prepend(d);setTimeout(()=>d.remove(),1600)}
function enemyType(){const r=Math.random();return state.wave>=5&&r<.16?'heavy':r<.32?'runner':'grunt'}
function spawnEnemy(){const spots=[[1,5],[17,5],[1,13],[17,13],[5,1],[13,1],[5,17],[13,17]];let s=spots[Math.floor(Math.random()*spots.length)],p=worldToPx(s[0],s[1]),t=enemyType(),e=enemyTypes[t];state.enemies.push({x:p.x,y:p.y,type:t,hp:e.hp,max:e.hp,speed:e.speed,phase:Math.random()*10,hit:0})}
function shoot(){if(paused||reloading||state.weapon.fireCd>0)return;if(state.weapon.mag<=0){reload();return}state.weapon.mag--;state.weapon.fireCd=1/state.weapon.fireRate;muzzle=.08;spawnMuzzle();const ox=state.player.x,oy=state.player.y, a=state.player.a;let hit=null,best=999;for(const e of state.enemies){const dx=e.x-ox,dy=e.y-oy,d=Math.hypot(dx,dy);const da=Math.atan2(Math.sin(Math.atan2(dy,dx)-a),Math.cos(Math.atan2(dy,dx)));if(Math.abs(da)<.085 && d<14 && clearRay(ox,oy,e.x,e.y) && d<best){hit=e;best=d}}
if(hit){let dmg=state.weapon.damage*(Math.random()<state.weapon.crit?2:1);hit.hp-=dmg;hit.hit=.08;state.score+=Math.floor(dmg);if(hit.hp<=0)kill(hit)}sfx('shot')}
function clearRay(ax,ay,bx,by){const n=Math.ceil(Math.hypot(bx-ax,by-ay)/10);for(let i=1;i<n;i++){const px=ax+(bx-ax)*i/n,py=ay+(by-ay)*i/n;if(solid(px,py))return false}return true}
function spawnMuzzle(){for(let i=0;i<5;i++)state.parts.push({x:state.player.x+Math.cos(state.player.a)*.6*world.cell,y:state.player.y+Math.sin(state.player.a)*.6*world.cell,vx:Math.cos(state.player.a+Math.random()*.7-.35)*Math.random()*160,vy:Math.sin(state.player.a+Math.random()*.7-.35)*Math.random()*160,life:.18,size:Math.random()*3+1})}
function kill(e){state.kills++;state.score+=enemyTypes[e.type].score;toast('TARGET DOWN  +'+enemyTypes[e.type].score);for(let i=0;i<12;i++)state.parts.push({x:e.x,y:e.y,vx:(Math.random()-.5)*170,vy:(Math.random()-.5)*170,life:.35+Math.random()*.25,size:2+Math.random()*3});state.enemies=state.enemies.filter(a=>a!==e)}
function reload(){if(reloading||state.weapon.mag>=12||state.weapon.reserve<=0)return;reloading=true;reloadT=.85;ui.reloadText.textContent='RELOADING'}
function damage(v){if(state.player.inv>0)return;let a=Math.min(state.player.armor,v*.65);state.player.armor-=a;let h=v-a;state.player.hp-=h;state.player.inv=.55;damageFlash=.28;if(state.player.hp<=0)die();sfx('hurt')}
function die(){running=false;paused=true;ui.finalScore.textContent=String(state.score).padStart(6,'0');ui.finalWave.textContent=String(state.wave).padStart(2,'0');ui.dead.classList.add('show')}
function nextWave(){paused=true;ui.upgrades.innerHTML='';const pick=[...upgrades].sort(()=>Math.random()-.5).slice(0,3);for(const u of pick){const d=document.createElement('div');d.className='upgrade';d.innerHTML=`<div class="tag">${u[0]}</div><h3>${u[1]}</h3><p>${u[2]}</p><button>SEÇ</button>`;d.querySelector('button').onclick=()=>{u[3]();ui.up.classList.remove('show');state.wave++;state.player.armor=state.player.maxArmor;paused=false;startWave();};ui.upgrades.appendChild(d)}ui.up.classList.add('show')}
function update(dt){if(paused)return;const p=state.player;if(p.inv>0)p.inv-=dt;state.weapon.fireCd=Math.max(0,state.weapon.fireCd-dt);if(reloading){reloadT-=dt;if(reloadT<=0){const take=Math.min(12,state.weapon.reserve);state.weapon.mag=take;state.weapon.reserve-=take;reloading=false;ui.reloadText.textContent='READY'}}
let mv={x:0,y:0};if(keys.w||keys.arrowup)mv.y-=1;if(keys.s||keys.arrowdown)mv.y+=1;if(keys.a||keys.arrowleft)mv.x-=1;if(keys.d||keys.arrowright)mv.x+=1;mv.x+=touch.mx;mv.y+=touch.my;mv=norm(mv);const sp=p.move*world.cell*dt*state.upg.move;const nx=p.x+mv.x*sp,ny=p.y+mv.y*sp;if(canMove(nx,p.y,.22))p.x=nx;if(canMove(p.x,ny,.22))p.y=ny;
if(touch.fire)shoot();for(let i=state.bullets.length-1;i>=0;i--)state.bullets.splice(i,1);
state.spawnTimer-=dt;if(state.spawn>0&&state.spawnTimer<=0){spawnEnemy();state.spawn--;state.spawnTimer=Math.max(.18,.62-state.wave*.025)}else if(state.spawn<=0&&state.enemies.length===0&& !ui.up.classList.contains('show'))nextWave();
for(const e of state.enemies){const dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;if(d>1.2*world.cell){const vx=dx/d*e.speed*world.cell*dt,vy=dy/d*e.speed*world.cell*dt;if(canMove(e.x+vx,e.y,.18))e.x+=vx;if(canMove(e.x,e.y+vy,.18))e.y+=vy}else if(Math.random()<dt*1.6)damage(enemyTypes[e.type].dmg);e.hit=Math.max(0,e.hit-dt)}
for(let i=state.parts.length-1;i>=0;i--){const q=state.parts[i];q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.93;q.vy*=.93;q.life-=dt;if(q.life<=0)state.parts.splice(i,1)}muzzle=Math.max(0,muzzle-dt);damageFlash=Math.max(0,damageFlash-dt);ui.flash.style.opacity=damageFlash*1.2;updateUI()}
function updateUI(){ui.wave.textContent=String(state.wave).padStart(2,'0');ui.score.textContent=String(state.score).padStart(6,'0');ui.hp.textContent=Math.max(0,Math.ceil(state.player?.hp||0));ui.armor.textContent=Math.max(0,Math.ceil(state.player?.armor||0));ui.ammo.textContent=state.weapon.mag;}
function render(){x.fillStyle='#05070b';x.fillRect(0,0,W,H);if(!state.player)return;const p=state.player, fov=Math.PI/2.9, rays=Math.max(180,Math.floor(W/3)), strip=W/rays, depth=new Float32Array(rays);
// sky/floor
x.fillStyle='#080b10';x.fillRect(0,0,W,H/2);x.fillStyle='#101317';x.fillRect(0,H/2,W,H/2);
for(let r=0;r<rays;r++){const ca=p.a-fov/2+fov*(r/rays);let d=0,hitSide=0;while(d<18){d+=.035;const rx=p.x+Math.cos(ca)*d*world.cell,ry=p.y+Math.sin(ca)*d*world.cell;if(solid(rx,ry)){hitSide=(Math.abs(Math.cos(ca))>.5?0:1);break}}d*=Math.cos(ca-p.a);depth[r]=d;const wh=Math.min(H*1.6,world.cell*H/(d*world.cell*.9));const y=H/2-wh/2;let shade=clamp(1-d/18,.08,1);let base=hitSide?'#33404a':'#27323a';x.fillStyle=shadeColor(base,shade);x.fillRect(r*strip,y,strip+1,wh)}
// distant floor grid
x.globalAlpha=.12;x.strokeStyle='#8fa0ad';for(let yy=H/2;yy<H;yy+=22){x.beginPath();x.moveTo(0,yy);x.lineTo(W,yy);x.stroke()}x.globalAlpha=1;
// enemies sorted by distance
const list=[...state.enemies].sort((a,b)=>dist(b,p)-dist(a,p));for(const e of list)drawEnemy(e,depth,fov,strip);
drawGun();
}
function shadeColor(hex,s){const n=parseInt(hex.slice(1),16),r=(n>>16)&255,g=(n>>8)&255,b=n&255;return`rgb(${r*s|0},${g*s|0},${b*s|0})`}
function drawEnemy(e,depth,fov,strip){const p=state.player,dx=e.x-p.x,dy=e.y-p.y,d=Math.hypot(dx,dy)/world.cell,da=Math.atan2(Math.sin(Math.atan2(dy,dx)-p.a),Math.cos(Math.atan2(dy,dx)));if(Math.abs(da)>fov*.62)return;const sx=W/2+(da/fov)*W, h=Math.min(H*1.2,H/d*(e.type==='heavy'?1.55:1.25)), w=h*enemyTypes[e.type].size/.42, idx=Math.floor(clamp((sx/W)*depth.length,0,depth.length-1));if(d>depth[idx]+.4)return;const top=H/2-h*.56;const col=enemyTypes[e.type].color;x.fillStyle=col;x.globalAlpha=e.hit>0?1:.92;x.fillRect(sx-w/2,top,w,h);x.globalAlpha=1;x.fillStyle='#111';x.fillRect(sx-w*.23,top+h*.25,w*.14,h*.08);x.fillRect(sx+w*.09,top+h*.25,w*.14,h*.08);x.fillStyle='#fff';x.fillRect(sx-w*.14,top+h*.28,w*.07,h*.035);x.fillRect(sx+w*.07,top+h*.28,w*.07,h*.035);x.fillStyle='rgba(0,0,0,.5)';x.fillRect(sx-w*.38,top-h*.12,w*.76,4);x.fillStyle='#c8ff52';x.fillRect(sx-w*.38,top-h*.12,w*.76*(e.hp/e.max),4)}
function drawGun(){const cx=W*.56,cy=H*.78;x.save();x.translate(cx,cy);x.rotate(state.player.a*.045);x.fillStyle='#171c22';x.beginPath();x.moveTo(-58,70);x.lineTo(-34,0);x.lineTo(40,-8);x.lineTo(82,34);x.lineTo(40,58);x.closePath();x.fill();x.fillStyle='#2e363d';x.fillRect(-3,-38,74,20);x.fillStyle='#07090c';x.fillRect(34,-44,75,9);x.fillStyle='#a8b1b8';x.fillRect(42,-42,52,4);x.fillStyle='#0d1116';x.fillRect(-36,40,22,50);if(muzzle>0){x.fillStyle='#e6ff8b';x.globalAlpha=.9;x.beginPath();x.moveTo(110,-39);x.lineTo(145,-20);x.lineTo(111,-5);x.lineTo(123,-23);x.closePath();x.fill();x.globalAlpha=1}x.restore();for(const q of state.parts){x.fillStyle='#e6ff8b';x.globalAlpha=clamp(q.life*2,0,1);x.fillRect(q.x%W,q.y%H,q.size,q.size);x.globalAlpha=1}}
function loop(t){const dt=Math.min(.033,(t-last)/1000||.016);last=t;if(running)update(dt);render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function sfx(kind){try{const A=window.AudioContext||window.webkitAudioContext;if(!window.ac)window.ac=new A();const o=window.ac.createOscillator(),g=window.ac.createGain();o.connect(g);g.connect(window.ac.destination);const f=kind==='shot'?170:kind==='hurt'?70:330;o.frequency.value=f;g.gain.setValueAtTime(.035,window.ac.currentTime);g.gain.exponentialRampToValueAtTime(.0001,window.ac.currentTime+.07);o.start();o.stop(window.ac.currentTime+.08)}catch{}}
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='r')reload();});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function lockLandscape(){const el=document.documentElement;try{if(document.documentElement.requestFullscreen&&!document.fullscreenElement)el.requestFullscreen().catch(()=>{});if(screen.orientation?.lock)screen.orientation.lock('landscape').catch(()=>{})}catch{}}
ui.play.onclick=()=>{lockLandscape();reset();running=true;sfx('start')};ui.again.onclick=()=>{lockLandscape();reset();running=true};
const pad=document.getElementById('moveStick'),dot=pad.querySelector('.stickDot');let movePointer=null;function setMove(px,py){const r=pad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,mx=clamp((px-cx)/(r.width/2),-1,1),my=clamp((py-cy)/(r.height/2),-1,1);touch.mx=mx;touch.my=my;dot.style.transform=`translate(${mx*28}px,${my*28}px)`}pad.addEventListener('pointerdown',e=>{movePointer=e.pointerId;pad.setPointerCapture(movePointer);setMove(e.clientX,e.clientY)});pad.addEventListener('pointermove',e=>{if(e.pointerId===movePointer)setMove(e.clientX,e.clientY)});pad.addEventListener('pointerup',e=>{if(e.pointerId===movePointer){movePointer=null;touch.mx=touch.my=0;dot.style.transform=''}});pad.addEventListener('pointercancel',()=>{movePointer=null;touch.mx=touch.my=0;dot.style.transform=''});
const look=document.getElementById('lookZone');look.addEventListener('pointerdown',e=>{touch.lookId=e.pointerId;touch.lastX=e.clientX;look.setPointerCapture(e.pointerId)});look.addEventListener('pointermove',e=>{if(e.pointerId===touch.lookId&&!paused){const dx=e.clientX-touch.lastX;touch.lastX=e.clientX;state.player.a+=dx*.005}});look.addEventListener('pointerup',()=>touch.lookId=null);look.addEventListener('pointercancel',()=>touch.lookId=null);
const fire=document.getElementById('fireBtn');fire.addEventListener('pointerdown',e=>{touch.fire=true;fire.setPointerCapture(e.pointerId);shoot()});fire.addEventListener('pointerup',()=>touch.fire=false);fire.addEventListener('pointercancel',()=>touch.fire=false);document.getElementById('reloadBtn').onclick=reload;document.getElementById('dashBtn').onclick=()=>{if(state.player.dashCd<=0){const p=state.player;const nx=p.x+Math.cos(p.a)*world.cell*1.6,ny=p.y+Math.sin(p.a)*world.cell*1.6;if(canMove(nx,ny,.22)){p.x=nx;p.y=ny}p.dashCd=2/state.upg.dash;}};
// Desktop mouse fallback for testing
addEventListener('mousemove',e=>{if(innerWidth>720&&running&&!paused){state.player.a+=(e.movementX||0)*.0025}});addEventListener('mousedown',()=>{if(innerWidth>720)touch.fire=true});addEventListener('mouseup',()=>touch.fire=false);addEventListener('click',()=>{if(innerWidth>720&&running)shoot()});
