(()=>{"use strict";
const $=s=>document.querySelector(s),canvas=$("#canvas"),ctx=canvas.getContext("2d"),mini=$("#minimap"),mctx=mini.getContext("2d");
const ui={menu:$("#menu"),hud:$("#hud"),mobile:$("#mobileControls"),play:$("#playBtn"),overlay:$("#roundOverlay"),next:$("#nextRound"),result:$("#result"),reason:$("#reason"),ally:$("#allyScore"),enemy:$("#enemyScore"),round:$("#roundLabel"),timer:$("#timer"),obj:$("#objective"),hp:$("#hp"),shield:$("#shield"),hpFill:$("#hpFill"),ammo:$("#ammo"),reloadText:$("#reloadText"),feed:$("#killFeed"),ret:$("#reticle"),hit:$("#hitConfirm"),flash:$("#damageFlash"),knob:$("#knob"),move:$("#moveZone"),look:$("#lookZone"),fire:$("#fireBtn"),reload:$("#reloadBtn"),jump:$("#jumpBtn"),crouch:$("#crouchBtn"),e:$("#eMobileBtn"),q:$("#qMobileBtn"),ult:$("#ult")};
let W=innerWidth,H=innerHeight,dpr=1,last=0,running=false,round=1,ally=0,enemy=0,time=100,fireHeld=false,recoil=0,muzzle=0,shake=0,fireCd=0,wasPortrait=false;
const coarse=matchMedia("(pointer:coarse)").matches;
const keys={},touch={x:0,y:0,active:false,id:null},look={active:false,id:null,x:0,y:0};
const p={x:0,y:0,rot:0,pitch:0,z:0,hp:100,shield:50,ammo:25,reserve:75,reload:0,stamina:100,alive:true};
const bounds={min:-14,max:14};
const walls=[{x:-10,y:-2,w:5,h:1.1},{x:6,y:3,w:5,h:1.1},{x:-2,y:6,w:1.2,h:6},{x:2,y:-8,w:1.2,h:6},{x:-11,y:8,w:4,h:1},{x:8,y:-8,w:4,h:1},{x:-1,y:-1,w:3,h:1},{x:-8,y:2,w:2.5,h:1}];
let bots=[];
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener("resize",resize);resize();
function portrait(){return innerHeight>innerWidth}
function resetBots(){bots=[];[[-11,-11],[11,11],[-11,10],[10,-10],[-6,12],[9,6],[-12,3]].forEach((a,i)=>bots.push({id:i,x:a[0],y:a[1],rot:0,hp:100,alive:true,speed:1.15+Math.random()*.5,strafe:Math.random()<.5?-1:1,alert:0,shot:1+Math.random()*1.7}))}
function startGame(){ui.menu.classList.add("hidden");ui.hud.classList.remove("hidden");if(coarse)ui.mobile.classList.remove("hidden");round=1;ally=0;enemy=0;ui.ally.textContent=0;ui.enemy.textContent=0;startRound()}
function startRound(){Object.assign(p,{x:0,y:0,rot:0,pitch:0,z:0,hp:100,shield:50,ammo:25,reserve:75,reload:0,alive:true});recoil=0;time=100;fireHeld=false;resetBots();ui.round.textContent="ROUND "+String(round).padStart(2,"0");ui.overlay.classList.add("hidden");running=true;last=performance.now();requestAnimationFrame(loop)}
ui.play.onclick=startGame;ui.next.onclick=()=>{round++;startRound()};
addEventListener("keydown",e=>{keys[e.code]=true;if(e.code==="KeyR")reload();if(e.code==="Space")jump();if(e.code==="KeyE")dash();if(e.code==="KeyQ")pulse()});
addEventListener("keyup",e=>keys[e.code]=false);
canvas.addEventListener("click",()=>{if(!coarse&&running)canvas.requestPointerLock?.()});
addEventListener("mousemove",e=>{if(!running||coarse||document.pointerLockElement!==canvas)return;p.rot+=e.movementX*.0028;p.pitch=clamp(p.pitch+e.movementY*.0022,-.44,.44)});
addEventListener("mousedown",e=>{if(e.button===0){fireHeld=true;if(!coarse)shoot()}});addEventListener("mouseup",e=>{if(e.button===0)fireHeld=false});
ui.fire.addEventListener("pointerdown",e=>{e.preventDefault();fireHeld=true;shoot()});["pointerup","pointercancel","pointerleave"].forEach(x=>ui.fire.addEventListener(x,e=>{e.preventDefault();fireHeld=false}));
ui.reload.addEventListener("pointerdown",e=>{e.preventDefault();reload()});ui.jump.addEventListener("pointerdown",e=>{e.preventDefault();jump()});ui.crouch.addEventListener("pointerdown",e=>{e.preventDefault();p.z=.1});ui.e.addEventListener("pointerdown",e=>{e.preventDefault();dash()});ui.q.addEventListener("pointerdown",e=>{e.preventDefault();pulse()});
ui.move.addEventListener("pointerdown",e=>{e.preventDefault();touch.active=true;touch.id=e.pointerId;ui.move.setPointerCapture(e.pointerId);joy(e)});
ui.move.addEventListener("pointermove",e=>{if(touch.active&&e.pointerId===touch.id)joy(e)});
ui.move.addEventListener("pointerup",()=>{touch.active=false;touch.x=touch.y=0;ui.knob.style.transform="translate(0,0)"});
function joy(e){const r=ui.move.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=48,l=Math.hypot(dx,dy),x=l>m?dx/l*m:dx,y=l>m?dy/l*m:dy;touch.x=x/m;touch.y=y/m;ui.knob.style.transform=`translate(${x}px,${y}px)`}
ui.look.addEventListener("pointerdown",e=>{if(!coarse)return;e.preventDefault();look.active=true;look.id=e.pointerId;look.x=e.clientX;look.y=e.clientY;ui.look.setPointerCapture(e.pointerId)});
ui.look.addEventListener("pointermove",e=>{if(!look.active||e.pointerId!==look.id)return;const dx=e.clientX-look.x,dy=e.clientY-look.y;p.rot+=dx*.006;p.pitch=clamp(p.pitch+dy*.003,-.44,.44);look.x=e.clientX;look.y=e.clientY});
ui.look.addEventListener("pointerup",()=>look.active=false);ui.look.addEventListener("pointercancel",()=>look.active=false);

function shoot(){if(!running||!p.alive||p.reload>0||fireCd>0)return;if(p.ammo<=0){reload();return}p.ammo--;fireCd=.105;muzzle=.055;recoil=clamp(recoil+.04,0,.115);shake=.07;const ang=p.rot+rand(-.015-recoil*.1,.015+recoil*.1),t=target(ang);if(t){const head=Math.random()<.2,dmg=head?145:34;t.hp-=dmg;t.alert=3;confirm(head);addFeed(`YOU → BOT ${t.id+1}`,head?"HEADSHOT":"HIT");if(t.hp<=0){t.alive=false;ally++;ui.ally.textContent=ally;addFeed(`ENEMY ${t.id+1}`,"ELIMINATED");if(bots.every(b=>!b.alive))end(true,"Tüm rakipler etkisiz.")}}}
function target(ang){let best=null,bd=99;for(const b of bots){if(!b.alive)continue;const dx=b.x-p.x,dy=b.y-p.y,d=Math.hypot(dx,dy),a=Math.atan2(dy,dx);if(d<25&&Math.abs(norm(a-ang))<Math.min(.07,.19/d)&&d<bd&&clear(p.x,p.y,b.x,b.y)){best=b;bd=d}}return best}
function reload(){if(p.reload>0||p.ammo>=25||p.reserve<=0)return;p.reload=1.2}
function jump(){if(p.z===0)p.z=.85}
function dash(){p.x+=Math.cos(p.rot)*5.8;p.y+=Math.sin(p.rot)*5.8;resolve(p);shake=.18}
function pulse(){bots.forEach(b=>{if(b.alive&&Math.hypot(b.x-p.x,b.y-p.y)<8)b.alert=5})}
function botShoot(b){const dx=p.x-b.x,dy=p.y-b.y,d=Math.hypot(dx,dy),a=Math.atan2(dy,dx);if(d>19||!clear(b.x,b.y,p.x,p.y)||Math.abs(norm(a-b.rot))>.14)return;b.shot=.55+Math.random()*.8;if(Math.random()<Math.max(.12,.45-d*.018))damage(9+Math.random()*7)}
function damage(d){if(!p.alive)return;const absorb=Math.min(p.shield,d*.62);p.shield-=absorb;d-=absorb;p.hp-=d;ui.flash.classList.add("show");setTimeout(()=>ui.flash.classList.remove("show"),90);shake=.18;if(p.hp<=0){p.hp=0;p.alive=false;enemy++;ui.enemy.textContent=enemy;end(false,"Oyuncu düşürüldü.")}}
function end(win,reason){if(!running)return;running=false;ui.result.textContent=win?"VICTORY":"DEFEAT";ui.result.style.color=win?"var(--green)":"var(--red)";ui.reason.textContent=reason;ui.overlay.classList.remove("hidden");fireHeld=false}
function update(dt){if(!running)return;fireCd=Math.max(0,fireCd-dt);recoil=Math.max(0,recoil-dt*.22);shake=Math.max(0,shake-dt*.7);muzzle=Math.max(0,muzzle-dt);if(p.reload>0){p.reload-=dt;if(p.reload<=0){const n=Math.min(25-p.ammo,p.reserve);p.ammo+=n;p.reserve-=n}}if(fireHeld)shoot();p.z=Math.max(0,p.z-dt*2.8);
let mx=0,my=0;if(keys.KeyW||keys.ArrowUp)my++;if(keys.KeyS||keys.ArrowDown)my--;if(keys.KeyA||keys.ArrowLeft)mx--;if(keys.KeyD||keys.ArrowRight)mx++;mx+=touch.x;my-=touch.y;let l=Math.hypot(mx,my);if(l>1){mx/=l;my/=l}let sp=5.1*(keys.ShiftLeft?.62:1);if(p.z>.2)sp*=1.05;const f=Math.cos(p.rot),g=Math.sin(p.rot),r=-g,s=f;p.x+=(f*my+r*mx)*sp*dt;p.y+=(g*my+s*mx)*sp*dt;resolve(p);
time-=dt;if(time<=0)end(bots.every(b=>!b.alive),"Süre sona erdi.");
bots.forEach(b=>{if(!b.alive)return;b.shot-=dt;const dx=p.x-b.x,dy=p.y-b.y,d=Math.hypot(dx,dy);if(clear(b.x,b.y,p.x,p.y)&&d<23){b.alert=3;b.rot=lerpAngle(b.rot,Math.atan2(dy,dx),dt*2.4)}else b.alert=Math.max(0,b.alert-dt);if(b.alert>0){b.x+=Math.cos(b.rot+Math.PI/2*b.strafe)*b.speed*dt*.55;b.y+=Math.sin(b.rot+Math.PI/2*b.strafe)*b.speed*dt*.55;resolve(b);if(b.shot<=0)botShoot(b)}else{b.x+=Math.cos(b.rot)*b.speed*.22*dt;b.y+=Math.sin(b.rot)*b.speed*.22*dt;if(Math.random()<.008)b.rot+=rand(-1,1);resolve(b)}});updateUI()}
function resolve(o){o.x=clamp(o.x,bounds.min+.6,bounds.max-.6);o.y=clamp(o.y,bounds.min+.6,bounds.max-.6);for(const w of walls){const cx=clamp(o.x,w.x,w.x+w.w),cy=clamp(o.y,w.y,w.y+w.h),dx=o.x-cx,dy=o.y-cy,d=Math.hypot(dx,dy);if(d<.5){if(Math.abs(dx)>Math.abs(dy))o.x+=(dx<0?-1:1)*(.5-Math.abs(dx));else o.y+=(dy<0?-1:1)*(.5-Math.abs(dy))}}}
function clear(x1,y1,x2,y2){for(const w of walls){for(let i=0;i<=28;i++){const t=i/28,x=x1+(x2-x1)*t,y=y1+(y2-y1)*t;if(x>=w.x&&x<=w.x+w.w&&y>=w.y&&y<=w.y+w.h)return false}}return true}
function project(x,y,z=0){const dx=x-p.x,dy=y-p.y,d=Math.hypot(dx,dy),a=norm(Math.atan2(dy,dx)-p.rot),hf=.82;if(d<.12||Math.abs(a)>hf)return null;const sx=W/2+Math.tan(a)/Math.tan(hf)*W*.5,horizon=H*.53-p.pitch*H*.65,scale=H/(d*2.45),sy=horizon-(z/d)*H*.9;return{sx,sy,scale,d}}
function draw(){const horizon=H*.53-p.pitch*H*.65;const sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,"#08121a");sky.addColorStop(1,"#17242c");ctx.fillStyle=sky;ctx.fillRect(0,0,W,horizon);const floor=ctx.createLinearGradient(0,horizon,0,H);floor.addColorStop(0,"#20282d");floor.addColorStop(1,"#0c1013");ctx.fillStyle=floor;ctx.fillRect(0,horizon,W,H-horizon);ctx.strokeStyle="rgba(255,255,255,.035)";for(let i=-18;i<=18;i++){ctx.beginPath();ctx.moveTo(W/2,horizon);ctx.lineTo(W/2+i*92,H);ctx.stroke()}const arr=[];walls.forEach(w=>arr.push({d:Math.hypot(w.x+w.w/2-p.x,w.y+w.h/2-p.y),w,type:0}));bots.forEach(b=>b.alive&&arr.push({d:Math.hypot(b.x-p.x,b.y-p.y),b,type:1}));arr.sort((a,b)=>b.d-a.d);arr.forEach(o=>o.type?drawBot(o.b):drawWall(o.w));drawGun();if(shake>0){ctx.fillStyle=`rgba(255,70,85,${shake*.06})`;ctx.fillRect(0,0,W,H)}}
function drawWall(w){const q=[project(w.x,w.y),project(w.x+w.w,w.y),project(w.x+w.w,w.y+w.h),project(w.x,w.y+w.h)];if(q.some(v=>!v))return;ctx.beginPath();ctx.moveTo(q[0].sx,q[0].sy);q.slice(1).forEach(v=>ctx.lineTo(v.sx,v.sy));ctx.closePath();const g=ctx.createLinearGradient(0,q[2].sy,0,q[0].sy);g.addColorStop(0,"#252f35");g.addColorStop(1,"#47545c");ctx.fillStyle=g;ctx.fill();ctx.strokeStyle="rgba(255,255,255,.12)";ctx.stroke();ctx.fillStyle="rgba(255,70,85,.13)";ctx.fillRect(Math.min(...q.map(v=>v.sx)),Math.min(...q.map(v=>v.sy)),Math.max(...q.map(v=>v.sx))-Math.min(...q.map(v=>v.sx)),2)}
function drawBot(b){const a=project(b.x,b.y),h=project(b.x,b.y,1.8);if(!a||!h)return;const Ht=a.sy-h.sy,w=Ht*.43,x=a.sx;ctx.fillStyle="rgba(0,0,0,.25)";ctx.beginPath();ctx.ellipse(x,a.sy, w*.7,5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#20272c";ctx.fillRect(x-w/2,a.sy-Ht*.63,w,Ht*.63);ctx.fillStyle="#3f4a51";ctx.fillRect(x-w*.42,a.sy-Ht*.6,w*.84,Ht*.45);ctx.fillStyle="#bec6ca";ctx.beginPath();ctx.arc(x,h.sy+Ht*.11,Ht*.1,0,Math.PI*2);ctx.fill();ctx.fillStyle=varColor("--red");ctx.fillRect(x-w*.3,h.sy+Ht*.19,w*.6,2);ctx.fillStyle="rgba(0,0,0,.55)";ctx.fillRect(x-w*.55,h.sy-8,w*1.1,3);ctx.fillStyle="#ff6674";ctx.fillRect(x-w*.55,h.sy-8,w*1.1*(b.hp/100),3)}
function drawGun(){const x=W*.67,y=H*.9-recoil*H;ctx.save();ctx.translate(x,y);ctx.rotate(-.06);ctx.fillStyle="#9e6d57";ctx.fillRect(-5,65,64,78);ctx.fillStyle="#1d2328";ctx.fillRect(16,72,62,35);const g=ctx.createLinearGradient(0,0,0,50);g.addColorStop(0,"#424b52");g.addColorStop(1,"#151a1e");ctx.fillStyle=g;ctx.fillRect(0,0,235,28);ctx.fillRect(84,18,110,40);ctx.fillRect(182,6,71,18);ctx.fillStyle="#080a0c";ctx.fillRect(222,8,51,9);ctx.fillStyle="#5a646b";ctx.fillRect(46,-5,12,20);ctx.fillStyle="#ff4655";ctx.fillRect(72,2,21,4);if(muzzle>0){ctx.fillStyle="#ffd66e";ctx.beginPath();ctx.moveTo(274,12);ctx.lineTo(307,1);ctx.lineTo(292,15);ctx.lineTo(314,26);ctx.closePath();ctx.fill()}ctx.restore()}
function drawMini(){const s=155/28,c=x=>12+(x+14)*s;mctx.clearRect(0,0,180,180);mctx.fillStyle="#081017";mctx.fillRect(0,0,180,180);walls.forEach(w=>{mctx.fillStyle="#354149";mctx.fillRect(c(w.x),c(w.y),w.w*s,w.h*s)});bots.forEach(b=>{if(b.alive){mctx.fillStyle="#ff4655";mctx.beginPath();mctx.arc(c(b.x),c(b.y),3.5,0,Math.PI*2);mctx.fill()}});mctx.fillStyle="#59e38c";mctx.beginPath();mctx.arc(c(p.x),c(p.y),4,0,Math.PI*2);mctx.fill();mctx.strokeStyle="#59e38c";mctx.beginPath();mctx.moveTo(c(p.x),c(p.y));mctx.lineTo(c(p.x)+Math.cos(p.rot)*11,c(p.y)+Math.sin(p.rot)*11);mctx.stroke()}
function updateUI(){ui.hp.textContent=Math.ceil(p.hp);ui.shield.textContent=Math.ceil(p.shield);ui.hpFill.style.width=Math.max(0,p.hp)+"%";ui.ammo.textContent=p.ammo;ui.reloadText.textContent=p.reload>0?"RELOADING":"";const t=Math.max(0,Math.ceil(time));ui.timer.textContent=String(Math.floor(t/60)).padStart(2,"0")+":"+String(t%60).padStart(2,"0")}
function confirm(head){ui.hit.textContent=head?"✦":"×";ui.hit.classList.add("show");ui.ret.classList.add("hit");setTimeout(()=>{ui.hit.classList.remove("show");ui.ret.classList.remove("hit")},120)}
function addFeed(a,b){const d=document.createElement("div");d.className="feed-item";d.textContent=a+" • "+b;ui.feed.prepend(d);setTimeout(()=>d.remove(),2400)}
function loop(t){if(!running)return;const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);ctx.save();const s=shake*18;ctx.translate(rand(-s,s),rand(-s,s));draw();ctx.restore();drawMini();requestAnimationFrame(loop)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function rand(a,b){return a+Math.random()*(b-a)}function norm(a){while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a}function lerpAngle(a,b,t){return a+norm(b-a)*clamp(t,0,1)}function varColor(name){return getComputedStyle(document.documentElement).getPropertyValue(name)}
setInterval(()=>{if(running&&portrait()&&!wasPortrait)wasPortrait=true},200);
})();
